---
title: "scAnnotatiONT paper"
author: "Nathalie Lehmann"
date: "`r Sys.Date()`"
output: bookdown::gitbook
documentclass: book
bibliography: []
biblio-style: apalike
link-citations: yes
github-repo: "https://github.com/LehmannN/scAnnotatiONT"
---

```{r setup-paths, echo=FALSE}
path_main <- './'
path_data <- paste0(path_main, 'data/')
path_output <- paste0(path_main, 'output/')
path_scripts <- paste0(path_main,'scripts/')
```

```{r setup-chunks, echo=FALSE, message=FALSE}
library(knitr)

# Change cache to TRUE if you need to re-run the analysis with small changes
# Careful: Bookdown doesn’t support proper cache invalidation based on external file changes
opts_chunk$set(fig.align = "center",
			   fig.retina = 2,
			   fig.width = 10,
			   cache = FALSE,
			   cache.lazy = FALSE,
			   warning = FALSE,
			   message = FALSE)
```

```{r def-libraries, echo=FALSE, cache=FALSE}
packagesList <- c("bookdown",
				   "knitr",
				   "rmarkdown",
				   "Seurat",
				   "scater",
				   "clusterProfiler",
				   "tidyseurat",
				   "monocle3",
				   "DT",
				   "ggplot2",
				   "Matrix",
				   "dplyr",
				   "RColorBrewer",
				   "viridis",
				   "wesanderson",
				   "gskb",
				   "ggExtra",
				   "ggpubr")

packagesList <- c("bookdown",
				  "dplyr", "eulerr")
lapply(packagesList, require, character.only = TRUE)
options(stringsAsFactors = FALSE)
```

```{r setup-knitr, include=FALSE}
# Automatically creates a bib database for R packages
knitr::write_bib(c(
				 .packages(), packagesList),
				 'env/packages.bib')
# Adds an option to show / hide the code dynamically in the report
#knitr::read_chunk('src/R/rmd_code_folding.R')
```

```{r ggplot-theme, echo=FALSE}
#Set ggplot theme
#theme_set(theme_classic())
```

